CAMERA_INDEX: int = 0

CAMERA_WIDTH: int = 400
CAMERA_HEIGHT: int = 300
DISPLAY_SCALE: float = 4.0
FULLSCREEN: bool = False 
FLIP_HORIZONTAL: bool = True

MAX_NUM_HANDS: int = 2
MODEL_COMPLEXITY: int = 0
MIN_DETECTION_CONFIDENCE: float = 0.5
MIN_TRACKING_CONFIDENCE: float = 0.5

DRAW_LANDMARKS: bool = True
DRAW_CONNECTIONS: bool = True
TEXT_COLOR_BGR = (50, 220, 50)
TEXT_BG_COLOR_BGR = (30, 30, 30)
TEXT_SCALE: float = 0.8
TEXT_THICKNESS: int = 2
MARGIN_PX: int = 10
